### ISSUE TITLE
emsg version 1 and 0

### ISSUE THREAD

**Issue by RufaelDev** [AOMediaCodec/id3-emsg#42] opened 2023-03-10 11:00 UTC
A question from our team, why is only version 1 supported, some devices may only support version 0 as this was introduced earlier. 

Is there any chance of also supporting version 0 for broader compatibility ?

**Comment by krasimirkolarov** [comment] 2023-03-22 17:48
From Roger - The ID3 carriage inside emsg was designed to support drop-in replacement of fMP4 for TS streams carrying ID3 timed metadata. As I recall, emsg version 1 was mandated because version 0 does not include a media time stamp, which was a requirement.

**Comment by RufaelDev** [comment] 2023-03-29 11:36
@krasimirkolarov and roger, thank you for the clarification and information, a question that came up, that as in CMAF both version 0 or version 1 of emsg are supported, this may make this spec incompatible with some CMAF implementations ? was this intended ? What would be the behaviour for a client/player that would get an incorrectly formatted message, such as based on version 0, would it be expected to fail gracefully or ignore the message ?

**Comment by roger-on-github** [comment] 2023-03-29 17:57
I don’t see how the spec is incompatible with CMAF. If CMAF allows both 0 and 1, then the spec falls within CMAF as it says to use 1. If you want to encode ID3 within emsg, that’s the way to do it inside CMAF.

I would expect players to ignore emsg boxes that contain a payload marked as ID3 with a version 0 emsg. At the same time, I would be sympathetic to any player that fired an error upon seeing a version 0 emsg marked with https://aomedia.org/emsg/ID3 since the spec clearly says that Version 1 of the Event Message box must be used. That’s a malformed file.

**Comment by porcelijn** [comment] 2023-03-31 06:56
So, to summarize and clarify: an ID3 payload with version 0 `emsg` is
* valid according to CMAF spec (though payload is undefined; the file violates none of the CMAF requirements)
* illegal according to id3-emsg spec. (the file is _malformed_)
A player is therefore expected to silently _ignore_ the ID3 payload with version 0 `emsg` rather than throw an error.

Is this summary correct?

**Comment by porcelijn** [comment] 2023-04-04 09:16
> So what you might expect is based mainly on how you imagine player authors write their code.

:smile: I stand corrected.
So HLS+CMAF (with id3 v0 emsg) being ignored by iPhone, crashing MediaStreamValidator and (potentially just working in HLS.js) — though suboptimal — are both according to spec.

A question about the TS heritage. As ID3 in transport streams clearly were not encapsulated in v1 (or v0) `emsg`, what timeline was the ID3 anchored to? If PCR, dts, or HLS media playlist, wouldn't fMP4 `tfdt` base media decode time be a sensible equivalent? (I'm probably all confused, please help me understand.)

**Comment by roger-on-github** [comment] 2023-04-04 15:58
Right, those client behaviors are within spec. (Although in the case of mediastreamvalidator, I think it would be great if someone were to file a bug at [feedbackassistant.apple.com](https://feedbackassistant.apple.com) so that (a) we can fix it to not crash, and (b) report the malformed bitstream.)

The spec for carriage of ID3 within TS for HLS is here: [Timed Metadata for HTTP Live Streaming](https://developer.apple.com/library/archive/documentation/AudioVideo/Conceptual/HTTP_Live_Streaming_Metadata_Spec/Introduction/Introduction.html). As you can see, ID3 tags are carried within Program Elementary Streams, so they have PES timestamps. These correspond closely to fMP4 sample timestamps.

fMP4 base media decode time ('tfdt') isn't quite right, as an ID3 tag might have a time in the middle of a fragment rather than at the beginning.

**Comment by porcelijn** [comment] 2023-04-05 09:53
Thanks for the great explanation & useful link.

> Bonus points for attaching sample content.
I'm sure we've notified Apple about the segfault, for reference here's a malformed Nielsen ID3 wrapped in  v0 `emsg`
```
0000 DAA5: 65 6D 73 67 00 00 00 00  68 74 74 70 3A 2F 2F 77  emsg.... http://w  
0000 DAB5: 77 77 2E 69 64 33 2E 6F  72 67 2F 00 35 30 32 00  ww.id3.o rg/.502.  
0000 DAC5: 00 00 EA 60 00 02 2B BD  FF FF FF FF 59 71 F2 77  ...`..+. ....Yq.w  
0000 DAD5: 49 44 33 04 00 20 00 00  02 05 50 52 49 56 00 00  ID3.. .. ..PRIV..  
0000 DAE5: 01 7B 00 00 77 77 77 2E  6E 69 65 6C 73 65 6E 2E  .{..www. nielsen.  
0000 DAF5: 63 6F 6D 2F 58 31 30 30  7A 64 43 49 47 65 49 6C  com/X100 zdCIGeIl  
0000 DB05: 67 5A 6E 6B 59 6A 36 55  76 51 3D 3D 2F 4B 38 55  gZnkYj6U vQ==/K8U  
0000 DB15: 70 78 34 43 6A 6D 55 49  73 73 32 6C 48 71 33 72  px4CjmUI ss2lHq3r  
0000 DB25: 77 58 67 3D 3D 2F 67 41  38 43 44 32 4F 76 6E 2D  wXg==/gA 8CD2Ovn-  
0000 DB35: 65 50 33 4F 72 61 69 41  49 41 73 4D 39 62 5A 6B  eP3OraiA IAsM9bZk  
0000 DB45: 55 64 30 74 4A 49 51 4E  5A 46 4B 6B 2D 32 37 4E  Ud0tJIQN ZFKk-27N  
0000 DB55: 6A 71 65 69 52 54 57 69  64 4E 37 72 46 63 33 5F  jqeiRTWi dN7rFc3_  
0000 DB65: 7A 72 44 66 5A 65 46 7A  36 64 6C 76 31 4F 54 35  zrDfZeFz 6dlv1OT5  
0000 DB75: 42 59 4C 33 45 6F 5A 66  58 77 30 64 36 5A 37 43  BYL3EoZf Xw0d6Z7C  
0000 DB85: 47 62 75 44 62 37 63 43  30 70 73 61 74 35 36 67  GbuDb7cC 0psat56g  
0000 DB95: 38 44 34 36 51 45 55 6D  69 4D 75 6D 49 61 51 70  8D46QEUm iMumIaQp  
0000 DBA5: 47 52 51 71 63 5A 35 78  72 52 4E 2D 68 56 58 37  GRQqcZ5x rRN-hVX7  
0000 DBB5: 45 49 4F 77 64 49 49 77  55 44 37 54 51 58 42 47  EIOwdIIw UD7TQXBG  
0000 DBC5: 50 2D 52 33 52 6A 5F 6B  64 39 4F 69 45 3D 2F 30  P-R3Rj_k d9OiE=/0  
0000 DBD5: 30 30 30 30 2F 33 37 36  32 34 2F 30 30 00 41 00  0000/376 24/00.A.
```
(Note: Above snippet uses incorrect schemeIdUri)

> fMP4 base media decode time ('tfdt') isn't quite right, as an ID3 tag might have a time in the middle of a fragment rather than at the beginning.

So essentially, we went from 5 bytes @90kHz accuracy to 64 bits (@ media timescale) with additional constraint that `emsg` presentation time be in future relative to fragment. Looks from a distance like base media decode time -relative addressing would have been a reasonable fit too. Afterall, with `emsg`v0 _unsigned_ presentationTimeOffset you get sample accurate time points *without* room for erroneously signalling ID3 in the past.

Things being what they are, I feel that mandating version 1 `emsg` in the spec is mostly the result of an oversight, I don't see a technical advantage to the limitation.

One more question. There have been past and may be future proposals to extend DASHEventMessageBox (`emsg`) with version=2, etc. If these would be included in (future version of) CMAF, how will that affect the AOM id3-emsg spec? IMO the spec would be more future proof (and more within the spirit of DashEvenMessageBox) if it were limited to defining scheme_id_uri, value, id, and payload and left the timing semantics to the CMAF/DASH specs.

**Comment by roger-on-github** [comment] 2023-04-05 16:39
Thanks for the content. I filed a bug internally; if it reproduces for us we'll fix it.

We can argue about whether mandating v1 was the best choice but at this point the spec is done and implementations are widely deployed. Unless there's an actual flaw I don't see a strong argument for altering it. Generally speaking the more alternatives a spec allows for doing roughly the same thing, the less interoperability you get. Different implementations tend to make different non-interoperable choices.

Similarly, if somebody defines emsg v2 some day, we can consider it in the light of new benefits it brings to ID3 carriage. If there aren't any then I don't expect we'd take the interop cost of admiting it into the ID3 spec.

**Comment by krasimirkolarov** [comment] 2023-04-11 18:45
Thank you everyone for the discussion. Closing the issue at this point

**Closed by krasimirkolarov** 2023-04-11 18:45 UTC

**Comment by porcelijn** [comment] 2023-05-10 09:20
FYI.: The MediaStreamValidator crash https://github.com/AOMediaCodec/id3-emsg/issues/42#issuecomment-1497221188 was originally reported to apple in https://feedbackassistant.apple.com/feedback/11921135
